server:
    port: 9000

security:
  basic:
    enable: false
  ignored: /**

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/userservice
    username: sa
    password:
    driverClassName: org.h2.Driver

kafka:
  kafkaBroker: localhost:9092
  calendarItemTopicName: calendar-items
  consumerGroupName: calendar-items-event-consumer

DMRTechnology:
  app:
    jwtSecret: vAaQfCJkzqP8cFALajRpv8ErmJoC2QnZECo0/yEGw6lmTz7BEcWX5qj46jJG34VVUS4WkarBzdOYa6ObbqA8yg==
    jwtExpirationMs: 86400000